![Google Drive Image](https://drive.google.com/uc?export=view&id=1zLi1EkeMV8U5nADzIndtPJj041F51g0y)

<h1><center>Laboratorio 2: Pandas üì∑</center></h1>

<center><strong>Introducci√≥n, Entorno de Desarrollo y Manejo de Arreglos con Numpy</strong></center>

### Cuerpo Docente:

- Profesor de Catedra: [Pablo Badilla](https://github.com/pbadillatorrealba/)
- Profesor Practico  : [Gabriel Iturra-Bocaz](https://giturra.cl)

### Reglas:

- **Grupos de 2 personas**.
- **Ausentes** deber√°n realizar la actividad solos.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente ser√°n respondidos por este medio.
- Pueden usar cualquer material del curso que estimen conveniente, si utiliza material extra debe citarlo.

### Temas a tratar:

- `Pandas` para manejo de datos estructurados.

### Objetivos principales del laboratorio

- Comprender y aprovechar las ventajas que nos ofrece la Liberia  `Pandas` para trabajar con datos estructurados. El objetivo principal de este laboratorio es que visualicen la potencia de esta herramienta frente a softwares como `Excel`.
- Verificar que el uso indiscriminado de `for` puede afectar en la eficiencia al procesar datos masivos (problema similar que el visto con `numpy`).

El objetivo principal de este laboratorio es tener un primer acercamiento a pandas, visualizando los beneficios que nos ofrece esta librer√≠a.

# Problemas

In [1]:
# En caso de no haber instalado estas librer√≠as
# intalarlas
!pip install openpyxl
!pip install plotly

# Librer√≠a Core del Lab.
import numpy as np
import pandas as pd
import plotly.express as px

Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (5.15.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly) (8.2.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly) (23.1)

## Carga y tareas exploratorias

1. Cargue el conjunto de datos llamado `students_grades.xlsx` utilizando `Pandas`.

In [2]:
df=pd.read_excel("students_grades.xlsx")

2.- Imprimir un mensaje con la cantidad de elemento por cada dimensi√≥n en el Dataframe.

In [3]:
df.shape
print(f"El Dataframe tiene {df.shape[0]} filas y {df.shape[1]} columnas.")

El Dataframe tiene 1400 filas y 10 columnas.

3.- Imprimir un mensaje con los nombres de las columnas que conforman el DataFrame:

In [4]:
df.columns
print(f"Los nombres de las columnas son: {list(df.columns)}")

Los nombres de las columnas son: ['Unnamed: 0', 'names', 'gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']

4.- Imprimir un mensaje con los nombres de los √≠ndices que conforman el DataFrame:

In [5]:
df.index
print(f"Los nombres de los √≠ndices son: {list(df.index)}")

Los nombres de los √≠ndices son: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399]

5.- Mostrar los primeros 5, los √∫ltimos 5 elementos del DataFrame y realice un muestreo de 5 elementos de forma aleatoria.

In [6]:
df.head(5)

,Unnamed: 0,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
1,1,Madeline Fuller,female,group C,some high school,standard,none,124.0,142.0,142.0
2,2,Daniel Rester,male,group E,associate's degree,standard,none,156.0,196.0,193.0
3,3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
4,4,Geraldine Hale,female,group A,associate's degree,standard,none,131.0,166.0,166.0

In [7]:
df.tail(5)

,Unnamed: 0,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1395,1395,Alexander Dillon,male,group D,associate's degree,standard,none,193.0,142.0,193.0
1396,1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1398,1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193.0,196.0,193.0
1399,1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0

In [8]:
df.sample(5)

,Unnamed: 0,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1234,1234,Mitchell Fisher,male,group B,associate's degree,standard,none,80.0,76.0,64.0
54,54,Marjorie Brown,female,group B,high school,standard,none,48.0,62.0,60.0
830,830,Robert Tarlton,male,group B,some high school,free/reduced,completed,49.0,50.0,52.0
1155,1155,Bobby Lloyd,male,group C,some college,standard,none,193.0,49.0,42.0
1176,1176,Wendy Lewis,female,group B,high school,standard,none,87.0,95.0,86.0

6.- Mostrar una descripci√≥n r√°pida de las variables num√©ricas del DataFrame (utilice un m√©todo de descripci√≥n visto en clases).

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   1400 non-null   int64
 1   names                        1400 non-null   object
 2   gender                       1400 non-null   object
 3   race/ethnicity               1400 non-null   object
 4   parental level of education  1400 non-null   object
 5   lunch                        1400 non-null   object
 6   test preparation course      1400 non-null   object
 7   math score                   1360 non-null   float64
 8   reading score                1360 non-null   float64
 9   writing score                1353 non-null   float64
dtypes: float64(3), int64(1), object(6)
memory usage: 109.5+ KB

In [10]:
df.describe()

       Unnamed: 0   math score  reading score  writing score
count   1400.0000  1360.000000    1360.000000    1353.000000
mean     699.5000    89.538971      93.086029      91.852919
std      404.2895    47.152422      46.385775      47.043570
min        0.0000     0.000000      17.000000      10.000000
25%      349.7500    59.000000      63.000000      62.000000
50%      699.5000    72.000000      76.000000      75.000000
75%     1049.2500    97.250000     100.000000     100.000000
max     1399.0000   196.000000     196.000000     196.000000

7.- Imprimir un mensaje con la cantidad de valores nulos (investigue el m√©todo `isna()` y `sum()` de los DataFrames).

In [11]:
valores=df.isna().sum()
columnas=df.columns

In [12]:
i=0
while i<10:
  print(f"En {columnas[i]} hay {valores[i]} nulos.")
  i += 1

En Unnamed: 0 hay 0 nulos.
En names hay 0 nulos.
En gender hay 0 nulos.
En race/ethnicity hay 0 nulos.
En parental level of education hay 0 nulos.
En lunch hay 0 nulos.
En test preparation course hay 0 nulos.
En math score hay 40 nulos.
En reading score hay 40 nulos.
En writing score hay 47 nulos.

8.- Imprimir un mensaje que detalle la cantidad de valores unicos (investigue `nunique()`) .

In [13]:
valores=df.nunique()
columnas=df.columns

In [14]:
i=0
while i<10:
  print(f"En {columnas[i]} hay {valores[i]} √∫nicos.")
  i += 1

En Unnamed: 0 hay 1400 √∫nicos.
En names hay 1153 √∫nicos.
En gender hay 2 √∫nicos.
En race/ethnicity hay 5 √∫nicos.
En parental level of education hay 6 √∫nicos.
En lunch hay 2 √∫nicos.
En test preparation course hay 2 √∫nicos.
En math score hay 96 √∫nicos.
En reading score hay 88 √∫nicos.
En writing score hay 92 √∫nicos.

9.- Imprimir un mensaje con el total de filas que contengan nombres duplicados (investigue `duplicated()` y su par√°metro `subset`).

In [15]:
duplicados=df.duplicated(subset=['names']).sum()
print(f"El total de filas con nombres duplicados es {duplicados}.")

El total de filas con nombres duplicados es 247.

10.- Mostrar las filas que contengan nombres sean duplicados (investigue `duplicated()` y su par√°metro `subset`).

In [16]:
query=df.duplicated(subset=['names'])
df.loc[query,:]

,Unnamed: 0,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
12,12,Rita Courtney,female,group B,some high school,standard,none,193.0,193.0,193.0
81,81,Elizabeth Quintero,female,group B,some college,standard,none,82.0,85.0,87.0
160,160,Michelle Gonzales,female,group B,some high school,standard,completed,60.0,70.0,74.0
170,170,Carla Mendoza,female,group D,associate's degree,free/reduced,none,43.0,60.0,58.0
176,176,Darlene Parker,female,group C,associate's degree,standard,none,54.0,61.0,58.0
...,...,...,...,...,...,...,...,...,...,...
1385,1385,James Crawford,male,group D,master's degree,standard,none,193.0,147.0,131.0
1390,1390,Gloria Bradford,female,group B,high school,standard,none,124.0,64.0,193.0
1393,1393,Adam Romero,male,group C,high school,standard,completed,124.0,193.0,49.0
1395,1395,Alexander Dillon,male,group D,associate's degree,standard,none,193.0,142.0,193.0
1398,1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193.0,196.0,193.0

### Limpieza de Datos

1.- Para evitar modificar (y quizas corromper) los datos originales, copie el dataframe en una nueva variable `df_limpio`.

In [17]:
df_limpio=df.copy()
df_limpio

,Unnamed: 0,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
1,1,Madeline Fuller,female,group C,some high school,standard,none,124.0,142.0,142.0
2,2,Daniel Rester,male,group E,associate's degree,standard,none,156.0,196.0,193.0
3,3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
4,4,Geraldine Hale,female,group A,associate's degree,standard,none,131.0,166.0,166.0
...,...,...,...,...,...,...,...,...,...,...
1395,1395,Alexander Dillon,male,group D,associate's degree,standard,none,193.0,142.0,193.0
1396,1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1398,1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193.0,196.0,193.0
1399,1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0

2.- Elimine las filas con nombres duplicados.

In [18]:
query=df_limpio.duplicated(subset=['names'])
df_limpio=df_limpio.loc[query==False,:]
df_limpio

,Unnamed: 0,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
1,1,Madeline Fuller,female,group C,some high school,standard,none,124.0,142.0,142.0
2,2,Daniel Rester,male,group E,associate's degree,standard,none,156.0,196.0,193.0
3,3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
4,4,Geraldine Hale,female,group A,associate's degree,standard,none,131.0,166.0,166.0
...,...,...,...,...,...,...,...,...,...,...
1392,1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0
1394,1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0
1396,1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1399,1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0

3.- Elimine todas las filas con valores nulos `NaN`.

In [19]:
df_limpio.isnull().sum()

Unnamed: 0                      0
names                           0
gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                     26
reading score                  26
writing score                  29
dtype: int64

In [20]:
query1=df_limpio["math score"].isnull()
query2=df_limpio["reading score"].isnull()
query3=df_limpio["writing score"].isnull()
query= query1 | query2 | query3
df_limpio=df_limpio.loc[query==False,:]
df_limpio

,Unnamed: 0,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
1,1,Madeline Fuller,female,group C,some high school,standard,none,124.0,142.0,142.0
2,2,Daniel Rester,male,group E,associate's degree,standard,none,156.0,196.0,193.0
3,3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
4,4,Geraldine Hale,female,group A,associate's degree,standard,none,131.0,166.0,166.0
...,...,...,...,...,...,...,...,...,...,...
1392,1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0
1394,1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0
1396,1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1399,1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0

4.- Filtre todas las filas que contengan notas en `math score`, `reading score`, `writing score` mayores a 100.

In [34]:
df_limpio.loc[:,["math score", "reading score", "writing score"]]
query1=df_limpio.loc[:,"math score"]<=100
query2=df_limpio.loc[:,"reading score"]<=100
query3=df_limpio.loc[:,"writing score"]<=100
query= query1 & query2 & query3
df_limpio=df_limpio.loc[query,:]
df_limpio

,Unnamed: 0,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Promedio
0,0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0,3.58
3,3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0,5.78
5,5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0,5.04
6,6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0,5.64
7,7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0,6.34
...,...,...,...,...,...,...,...,...,...,...,...
1392,1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0,5.30
1394,1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0,3.06
1396,1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0,5.42
1397,1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0,4.54
1399,1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0,5.48

### Tratamiento de Datos

1. Transforme todas las notas porcentuales a la escala chilena, para esto utilice la ecuaci√≥n dispuesta m√°s abajo y aplic√°ndola solamente en las notas porcentuales. El desarrollo de esto deber√° ser sin uso de `for` y aprovechando los beneficios de pandas.

$$ Nota \, Chilena= \% \, de \, logro*0.06 + 1$$

In [35]:
nota_math=df_limpio["math score"]*0.06+1
nota_reading=df_limpio["reading score"]*0.06+1
nota_writing=df_limpio["writing score"]*0.06+1

2. Para cada uno de los alumnos cree una nueva columna que posea el promedio de todas las asignaturas cursadas. Tenga precauci√≥n en que las notas promediadas est√©n en la escala de notas chilena.

In [36]:
promedio=(nota_math+nota_reading+nota_writing)/3
df_limpio["Promedio"]=promedio
df_limpio

,Unnamed: 0,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Promedio
0,0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0,3.58
3,3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0,5.78
5,5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0,5.04
6,6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0,5.64
7,7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0,6.34
...,...,...,...,...,...,...,...,...,...,...,...
1392,1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0,5.30
1394,1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0,3.06
1396,1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0,5.42
1397,1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0,4.54
1399,1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0,5.48

3.- Utilizando el promedio general calculado en la pregunta anterior, identifique los alumnos que reprobaron el semestre (promedio inferior a 4.0).

In [37]:
query=df_limpio.loc[:,"Promedio"]<4.0
df_limpio.loc[query,:]

,Unnamed: 0,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Promedio
0,0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0,3.58
13,13,Mikki Amaya,female,group A,high school,free/reduced,completed,34.0,48.0,41.0,3.46
26,26,Samuel Dougal,male,group C,master's degree,free/reduced,completed,46.0,42.0,46.0,3.68
55,55,Rodger Talavera,male,group B,high school,free/reduced,none,36.0,29.0,27.0,2.84
63,63,Morris Johnson,male,group A,associate's degree,free/reduced,completed,40.0,55.0,53.0,3.96
...,...,...,...,...,...,...,...,...,...,...,...
1371,1371,Charles Harian,male,group C,some high school,free/reduced,completed,45.0,52.0,49.0,3.92
1373,1373,Wendy Gunnell,female,group D,some high school,free/reduced,none,27.0,34.0,32.0,2.86
1389,1389,Diana Costa,female,group C,high school,free/reduced,none,41.0,46.0,43.0,3.60
1391,1391,Amy Sieving,female,group C,high school,standard,none,29.0,29.0,30.0,2.76
1394,1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0,3.06

4.- Con los promedios obtenidos para cada uno de los alumnos, busque utilizando el comando `.isin()` los siguientes alumnos:

`['Lucille Stanphill','Marcus Mcfarland', 'Matthew Freeman', 'Dana Mojica', 'Paul Hyder', 'Jeffrey Korn', 'Robert Strain',
'Ronald Jett', 'Lorena Reed', 'Hazel Posey']`

In [38]:
query=df_limpio["names"].isin(['Lucille Stanphill','Marcus Mcfarland', 'Matthew Freeman', 'Dana Mojica', 'Paul Hyder', 'Jeffrey Korn', 'Robert Strain', 'Ronald Jett', 'Lorena Reed', 'Hazel Posey'])
df_limpio.loc[query,:]

,Unnamed: 0,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Promedio
296,296,Lucille Stanphill,female,group C,high school,standard,none,81.0,84.0,82.0,5.94
564,564,Marcus Mcfarland,male,group C,bachelor's degree,standard,completed,63.0,64.0,66.0,4.86
637,637,Matthew Freeman,male,group B,high school,standard,completed,52.0,49.0,46.0,3.94
640,640,Dana Mojica,female,group D,high school,free/reduced,none,39.0,52.0,46.0,3.74
1054,1054,Robert Strain,male,group C,associate's degree,free/reduced,none,55.0,61.0,54.0,4.40
1065,1065,Ronald Jett,male,group D,high school,free/reduced,none,42.0,39.0,34.0,3.30
1068,1068,Hazel Posey,female,group B,some high school,free/reduced,none,24.0,38.0,27.0,2.78
1195,1195,Lorena Reed,female,group C,high school,free/reduced,none,36.0,53.0,43.0,3.64

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87110296-876e-426f-b91d-aaf681223468' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>