![Google Drive Image](https://drive.google.com/uc?export=view&id=1zLi1EkeMV8U5nADzIndtPJj041F51g0y)

<h1><center>Laboratorio 4: Pandas üì∑</center></h1>

<center><strong>Combinaci√≥n de datasets y trabajo con texto y datos temporales</strong></center>

### Cuerpo Docente:

- Profesor de Catedra: [Pablo Badilla](https://github.com/pbadillatorrealba/)
- Profesor Practico  : [Gabriel Iturra-Bocaz](https://giturra.cl/)

### Reglas:

- **Grupos de 2 personas**.
- **Ausentes** deber√°n realizar la actividad solos.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente ser√°n respondidos por este medio.
- Pueden usar cualquer material del curso que estimen conveniente, si utiliza material extra debe citarlo.

### Objetivos principales del laboratorio

- Utilizar las herramientas que dispone pandas para trabajar eficientemente al mezclar informaci√≥n, revisar texto y fechas.

In [1]:
# En caso de no haber instalado estas librer√≠as
# intalarlas
#!pip install openpyxl

# Librer√≠a Core del Lab.
import numpy as np
import pandas as pd

## Merge

Para la siguiente pregunta seguiremos trabajando con los datasets de las notas estudiantiles, por lo que es necesario ejecutar la siguiente celda:

In [2]:
df_grades_1 = pd.read_json("https://raw.githubusercontent.com/pbadillatorrealba/DEDCCPYAC02-recursos/master/labs/lab3/students_grades_1.json")
df_grades_2 = pd.read_json("https://raw.githubusercontent.com/pbadillatorrealba/DEDCCPYAC02-recursos/master/labs/lab3/students_grades_2.json")

df_grades = pd.concat([df_grades_1, df_grades_2], axis=0)
df_grades

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,3.22,3.76,3.76
1,Charles Linstrom,male,group A,bachelor's degree,standard,completed,5.80,5.68,5.86
2,Brian Young,male,group C,some high school,standard,none,5.38,4.96,4.78
3,Howard Jimenez,male,group E,some high school,standard,completed,5.86,5.50,5.56
4,Wayne Wilson,male,group B,some high school,standard,completed,6.64,6.16,6.22
...,...,...,...,...,...,...,...,...,...
470,Richard Young,male,group D,high school,standard,none,5.14,5.50,5.26
471,Wanda Russell,female,group B,high school,free/reduced,completed,2.38,3.64,3.16
472,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,4.96,5.44,5.86
473,Laurie Carter,female,group B,some high school,standard,completed,4.24,4.66,4.72
474,Amanda Perez,female,group A,high school,standard,completed,5.08,5.80,5.56

Cargue el archivo [`other_grades.csv`](https://raw.githubusercontent.com/pbadillatorrealba/DEDCCPYAC02-recursos/master/labs/lab4/other_grades.csv), realice los siguientes `merge` y comente que es lo que realiza cada uno de ellos:
- [ ] Unir `df_grades` con `other_grades.csv` usando outer join y explique el resultado.
- [ ] Unir `df_grades` con `other_grades.csv` usando left join y explique el resultado.
- [ ] Unir `df_grades` con `other_grades.csv` usando right join y explique el resultado.
- [ ] Unir `df_grades` con `other_grades.csv` usando inner join y explique el resultado.

Finalmente, escoja alguno de los `merge` aplicados anteriormente para generar un nuevo `Dataframe` llamado `df_merged`, comente y justifique su elecci√≥n.

**NOTA:** Antes de generar el `merge` preste atenci√≥n en los nuevos datos que esta cargando.

In [3]:
df_other =pd.read_csv("https://raw.githubusercontent.com/pbadillatorrealba/DEDCCPYAC02-recursos/master/labs/lab4/other_grades.csv")
df_other

     Unnamed: 0              names  science score  history score
0             0         Pam Otoole           4.42            4.0
1             1        Diane Olson           3.88            4.8
2             2     Sarah Flannery           5.32            6.1
3             3   Stanley Chappell           3.82            3.7
4             4      Arnold Dodson           4.60            5.2
..          ...                ...            ...            ...
995         995    Melanie Acevedo           5.74            6.3
996         996   Christopher Wall           4.72            4.0
997         997  Margaret Spannaus           3.82            4.0
998         998     Vickie Sellers           3.82            5.7
999         999      Kari Mitchell           4.18            6.2

[1000 rows x 4 columns]

In [4]:
#Inner
pd.merge(left=df_grades,
         right=df_other,
         on="names",
         how="inner",
         sort=True)

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Unnamed: 0,science score,history score
0,Aaron Oakden,male,group D,high school,free/reduced,none,4.96,5.44,5.14,792,3.76,4.6
1,Aaron Shelly,male,group D,associate's degree,standard,none,4.66,3.88,3.76,627,3.88,3.9
2,Adam Romero,male,group C,high school,standard,completed,4.18,4.12,3.94,524,3.52,3.2
3,Agatha Bergman,female,group D,master's degree,standard,none,6.52,7.00,7.00,957,6.52,5.2
4,Agnes Dobbs,female,group C,master's degree,free/reduced,completed,4.90,5.86,5.86,259,4.90,5.9
...,...,...,...,...,...,...,...,...,...,...,...,...
870,William Saska,male,group B,associate's degree,standard,none,4.66,3.52,3.46,867,4.24,2.8
871,William Tang,male,group D,associate's degree,standard,none,5.50,5.08,4.84,436,4.12,4.7
872,Willie Gilbert,male,group E,some high school,standard,none,5.92,5.02,4.66,853,5.38,3.8
873,Willie Neff,female,group E,associate's degree,free/reduced,none,5.38,5.56,5.68,691,4.48,4.6
874,Willie Nicholson,female,group D,some college,free/reduced,completed,4.78,5.80,5.80,563,4.78,4.8

```
Inner merge busca los elementos comunes de las columnas elegidas,
en este caso "names", y combina la informaci√≥n de ambos dataframes en uno solo.
En este caso, encontr√≥ 875 estudiantes comunes, y agreg√≥ las 3 columnas del dataframe 2 que no eran "names",
a la derecha del primer dataframe.
```

In [5]:
#Outer
pd.merge(left=df_grades,
         right=df_other,
         on="names",
         how="outer",
         sort=True)

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Unnamed: 0,science score,history score
0,Aaron Oakden,male,group D,high school,free/reduced,none,4.96,5.44,5.14,792,3.76,4.6
1,Aaron Shelly,male,group D,associate's degree,standard,none,4.66,3.88,3.76,627,3.88,3.9
2,Adam Romero,male,group C,high school,standard,completed,4.18,4.12,3.94,524,3.52,3.2
3,Agatha Bergman,female,group D,master's degree,standard,none,6.52,7.00,7.00,957,6.52,5.2
4,Agnes Dobbs,female,group C,master's degree,free/reduced,completed,4.90,5.86,5.86,259,4.90,5.9
...,...,...,...,...,...,...,...,...,...,...,...,...
995,William Tang,male,group D,associate's degree,standard,none,5.50,5.08,4.84,436,4.12,4.7
996,Willie Gilbert,male,group E,some high school,standard,none,5.92,5.02,4.66,853,5.38,3.8
997,Willie Neff,female,group E,associate's degree,free/reduced,none,5.38,5.56,5.68,691,4.48,4.6
998,Willie Nicholson,female,group D,some college,free/reduced,completed,4.78,5.80,5.80,563,4.78,4.8
999,Zachary Glenn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,306,6.94,5.7

```
Outer merge combina todos los elementos de ambos dataframes. En este caso, hicimos el merge con la columna "names",
si un nombre no est√° en un dataframe,
rellena con NaN la informaci√≥n que deber√≠a estar guardada ah√≠.


```

In [ ]:
#Right
pd.merge(left=df_grades,
         right=df_other,
         on="names",
         how="right",
         sort=True)

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Unnamed: 0,science score,history score
0,Aaron Oakden,male,group D,high school,free/reduced,none,4.96,5.44,5.14,792,3.76,4.6
1,Aaron Shelly,male,group D,associate's degree,standard,none,4.66,3.88,3.76,627,3.88,3.9
2,Adam Romero,male,group C,high school,standard,completed,4.18,4.12,3.94,524,3.52,3.2
3,Agatha Bergman,female,group D,master's degree,standard,none,6.52,7.00,7.00,957,6.52,5.2
4,Agnes Dobbs,female,group C,master's degree,free/reduced,completed,4.90,5.86,5.86,259,4.90,5.9
...,...,...,...,...,...,...,...,...,...,...,...,...
995,William Tang,male,group D,associate's degree,standard,none,5.50,5.08,4.84,436,4.12,4.7
996,Willie Gilbert,male,group E,some high school,standard,none,5.92,5.02,4.66,853,5.38,3.8
997,Willie Neff,female,group E,associate's degree,free/reduced,none,5.38,5.56,5.68,691,4.48,4.6
998,Willie Nicholson,female,group D,some college,free/reduced,completed,4.78,5.80,5.80,563,4.78,4.8
999,Zachary Glenn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,306,6.94,5.7

```
Right merge mantiene todos los elementos del dataframe elegido como right, que en este caso son 1000.
Agrega a la izquierda los elementos del dataframe left, pero solo los que comparta con el de la derecha.
Si un nombre de la derecha no est√° en el dataframe de la izquierda, rellena la informaci√≥n con NaN.
```

In [ ]:
#Left
pd.merge(left=df_grades,
         right=df_other,
         on="names",
         how="left",
         sort=True)

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Unnamed: 0,science score,history score
0,Aaron Oakden,male,group D,high school,free/reduced,none,4.96,5.44,5.14,792,3.76,4.6
1,Aaron Shelly,male,group D,associate's degree,standard,none,4.66,3.88,3.76,627,3.88,3.9
2,Adam Romero,male,group C,high school,standard,completed,4.18,4.12,3.94,524,3.52,3.2
3,Agatha Bergman,female,group D,master's degree,standard,none,6.52,7.00,7.00,957,6.52,5.2
4,Agnes Dobbs,female,group C,master's degree,free/reduced,completed,4.90,5.86,5.86,259,4.90,5.9
...,...,...,...,...,...,...,...,...,...,...,...,...
870,William Saska,male,group B,associate's degree,standard,none,4.66,3.52,3.46,867,4.24,2.8
871,William Tang,male,group D,associate's degree,standard,none,5.50,5.08,4.84,436,4.12,4.7
872,Willie Gilbert,male,group E,some high school,standard,none,5.92,5.02,4.66,853,5.38,3.8
873,Willie Neff,female,group E,associate's degree,free/reduced,none,5.38,5.56,5.68,691,4.48,4.6
874,Willie Nicholson,female,group D,some college,free/reduced,completed,4.78,5.80,5.80,563,4.78,4.8

```
Left merge mantiene todos los elementos del dataframe elegido como left, que en este caso son 875.
Agrega a la derecha los elementos del dataframe right, pero solo los que comparta con el de la izquierda.
Si un nombre de la izquierda no est√° en el dataframe de la derecha, rellena la informaci√≥n con NaN.```

In [11]:
df_merged=pd.merge(left=df_grades,
         right=df_other,
         on="names",
         how="inner",
         sort=True).drop('Unnamed: 0', axis=1)
df_merged

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,science score,history score
0,Aaron Oakden,male,group D,high school,free/reduced,none,4.96,5.44,5.14,3.76,4.6
1,Aaron Shelly,male,group D,associate's degree,standard,none,4.66,3.88,3.76,3.88,3.9
2,Adam Romero,male,group C,high school,standard,completed,4.18,4.12,3.94,3.52,3.2
3,Agatha Bergman,female,group D,master's degree,standard,none,6.52,7.00,7.00,6.52,5.2
4,Agnes Dobbs,female,group C,master's degree,free/reduced,completed,4.90,5.86,5.86,4.90,5.9
...,...,...,...,...,...,...,...,...,...,...,...
870,William Saska,male,group B,associate's degree,standard,none,4.66,3.52,3.46,4.24,2.8
871,William Tang,male,group D,associate's degree,standard,none,5.50,5.08,4.84,4.12,4.7
872,Willie Gilbert,male,group E,some high school,standard,none,5.92,5.02,4.66,5.38,3.8
873,Willie Neff,female,group E,associate's degree,free/reduced,none,5.38,5.56,5.68,4.48,4.6
874,Willie Nicholson,female,group D,some college,free/reduced,completed,4.78,5.80,5.80,4.78,4.8

Para el dataframe df_merged eligir√≠a el inner merge, es decir, me quedar√≠a con los nombres de alumnos que est√°n en ambos dataframes, para tener la informaci√≥n completa de sus scores, y evitar tener valores nulos (correspondientes a los puntajes de math, reading y writing). La elecci√≥n podr√≠a variar, dependiendo del por qu√© hay alumnos que no tiene esos puntajes, quiz√°s estaban eximidos? o a√∫n no dal el test? O la informaci√≥n se encuentra en otro archivo?
Pero en este caso, probablemente necesitemos calcular alg√∫n puntaje final donde cada score tenga asociado un porcentaje, por lo que trabajar con nulos dificultar√≠a el proceso. Una opci√≥n ser√≠a reemplazarlos por 0.

Carga y Tratamiento de Datos

1.-Cargue el conjunto de datos [`reviews.csv`](https://raw.githubusercontent.com/pbadillatorrealba/DEDCCPYAC02-recursos/master/labs/lab4/reviews.csv) y observe lo que contiene el conjunto de datos. Se√±ale brevemente que representa cada una de las columnas.

In [151]:
df_reviews=pd.read_csv("https://raw.githubusercontent.com/pbadillatorrealba/DEDCCPYAC02-recursos/master/labs/lab4/reviews.csv")
df_reviews.head(5)

,Unnamed: 0.1,Unnamed: 0,book_title,date,rname,rating,review,likes,stars_given
0,0,0,Dune,"Mar 22, 2011",Rajat Ubhaykar,it was amazing,"In my head, the purpose of this review is very...",1130 likes,5.0
1,1,1,Dune,"Apr 29, 2014",Jay,did not like it,If this is the gold standard against which all...,1302 likes,1.0
2,2,2,Dune,"Nov 20, 2008",Manny,really liked it,There's a characteristically witty essay by Bo...,1890 likes,4.0
3,3,3,Dune,"Jun 24, 2007",John Wiswell,it was ok,No one should argue the importance Dune. It la...,1409 likes,2.0
4,4,4,Dune,"Nov 13, 2021",Lala BooksandLala,it was amazing,just when you thought 2021 couldn't get any we...,974 likes,5.0

Las dos primeras columas representan la posici√≥n de los libros en el dataframe, por lo que se podr√≠an borrar, es informaci√≥n repetida. Despu√©s book_title es el t√≠tulo del libro, date es la fecha en la que se escribi√≥ el review, rname es el nombre de la persona que escribi√≥ el review, rating es en breves palabras qu√© le pareci√≥ el libro, review es un comentario m√°s exhaustivo/explicaci√≥n del rating dado, likes es el n√∫mero de likes que recibi√≥ el review (me imagino que los reviews se publicaron en alguna plataforma, donde otros usuarios pueden darle like), y stars_given el n√∫mero de estrellas, o rating puesto como un n√∫mero.

2.- Extraiga el n√∫mero de likes a partir de los valores de la columna likes. Para esto:
- Procese la serie de texto eliminando las palabras "likes" y "like"
- Elimine los espacios iniciales y finales resultante de la operaci√≥n anterior.
- Rellene los valores faltantes con nan
- Converta la serie producida a entero
- Asigne la nueva serie al dataframe original para reemplazar la columna original por la preprocesada.

In [15]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  1800 non-null   int64
 1   Unnamed: 0    1800 non-null   int64
 2   book_title    1800 non-null   object
 3   date          1800 non-null   object
 4   rname         1800 non-null   object
 5   rating        1770 non-null   object
 6   review        1800 non-null   object
 7   likes         1799 non-null   object
 8   stars_given   1770 non-null   float64
dtypes: float64(1), int64(2), object(6)
memory usage: 126.7+ KB

In [152]:
#Veo que en la columna likes hay un solo valor nulo, lo identificar√© (s√© que no es necesario)
df_reviews["likes"].isnull()
df_reviews["likes"][df_reviews["likes"].isnull()]

1340    NaN
Name: likes, dtype: object

In [153]:
#reemplazar likes y like por nada, y el NaN por un valor 0.
convertido=df_reviews["likes"].str.replace("likes|like","", regex=True).str.strip().fillna("0").astype(int)
convertido

0       1130
1       1302
2       1890
3       1409
4        974
        ...
1795      11
1796      11
1797      11
1798      11
1799      10
Name: likes, Length: 1800, dtype: int64

In [154]:
df_reviews["likes"]=convertido
df_reviews

,Unnamed: 0.1,Unnamed: 0,book_title,date,rname,rating,review,likes,stars_given
0,0,0,Dune,"Mar 22, 2011",Rajat Ubhaykar,it was amazing,"In my head, the purpose of this review is very...",1130,5.0
1,1,1,Dune,"Apr 29, 2014",Jay,did not like it,If this is the gold standard against which all...,1302,1.0
2,2,2,Dune,"Nov 20, 2008",Manny,really liked it,There's a characteristically witty essay by Bo...,1890,4.0
3,3,3,Dune,"Jun 24, 2007",John Wiswell,it was ok,No one should argue the importance Dune. It la...,1409,2.0
4,4,4,Dune,"Nov 13, 2021",Lala BooksandLala,it was amazing,just when you thought 2021 couldn't get any we...,974,5.0
...,...,...,...,...,...,...,...,...,...
1795,1795,1795,Neuromancer,"Jan 23, 2013",Lit Bug,really liked it,Neuromancer is a seminal archetypal cyberpunk ...,11,4.0
1796,1796,1796,Neuromancer,"Sep 28, 2014",David Sarkies,it was ok,A journey into the heart of the machine4 Octob...,11,2.0
1797,1797,1797,Neuromancer,"Jul 07, 2014",Michael Emond,it was amazing,I decided to revisit this sci-fi classic I had...,11,5.0
1798,1798,1798,Neuromancer,"Nov 02, 2019",Oleksandr Zholud,really liked it,"This is the book that spawned the genre, cyber...",11,4.0
1799,1799,1799,Neuromancer,"Sep 13, 2016",Jonathan Pool,it was amazing,Historical & Literary contextI first read Neur...,10,5.0

3. En los siguientes tres puntos deber√° generar un detector de sentimientos basado en la cantidad de palabras positivas y negativas que posee cada review. El primer paso para esto es:

- Preprocesar la columna `review` convirtiendo todos los caracteres a min√∫sculas y elimine todos los acentos y puntuaciones. Para eliminar puntuaciones, efectue una b√∫squeda en google en ingles del estilo *como eliminar puntuaciones en pandas*.
- Separar las palabras de cada fila usando espacio como separador.

In [155]:
reviews=df_reviews["review"].str.lower().str.replace('[^\w\s]', " ",regex=True).str.replace('\s+', ' ', regex=True).str.split(" ")
reviews

0       [in, my, head, the, purpose, of, this, review,...
1       [if, this, is, the, gold, standard, against, w...
2       [there, s, a, characteristically, witty, essay...
3       [no, one, should, argue, the, importance, dune...
4       [just, when, you, thought, 2021, couldn, t, ge...
                              ...
1795    [neuromancer, is, a, seminal, archetypal, cybe...
1796    [a, journey, into, the, heart, of, the, machin...
1797    [i, decided, to, revisit, this, sci, fi, class...
1798    [this, is, the, book, that, spawned, the, genr...
1799    [historical, literary, contexti, first, read, ...
Name: review, Length: 1800, dtype: object

4.- Genere las series `positive` y ``negative`` aplicando sobre las `reviews` procesadas las funciones `contar_positivas` y `contar_negativas`. As√≠gnelos resultados obtenidos a una nueva columna.

In [119]:
# El siguiente c√≥digo contiene las palabras positivas y negativas que ser√°n contadas en cada review.
# No deber√≠an modificarlo, solo aplicarlo para generar las series que cuentan cuantos positivos y negativos tiene cada fila.

palabras_positivas = [
    "acclaimed",
    "affirmative",
    "affluent",
    "angelic",
    "beaming",
    "bliss",
    "bountiful",
    "bubbly",
    "commend",
    "dazzling",
    "earnest",
    "ecstatic",
    "effervescent",
    "enchanting",
    "exquisite",
    "graceful",
    "instinctive",
    "intellectual",
    "jovial",
    "jubilant",
    "lucid",
    "marvelous",
    "novel",
    "nurturing",
    "poised",
    "robust",
    "stirring",
    "stupendous",
    "thriving",
    "tranquil",
    "unwavering",
    "upbeat",
    "virtuous",
    "vivacious",
    "zealous",
]


def contar_positivas(lista_palabras):
    numero_palabras_positivas = 0
    for palabra_positiva in palabras_positivas:
        if palabra_positiva in lista_palabras:
            numero_palabras_positivas += 1

    return numero_palabras_positivas


palabras_negativas = [
    "abysmal",
    "apathy",
    "atrocious",
    "bemoan",
    "cold-hearted",
    "deplorable",
    "despicable",
    "detrimental",
    "dreadful",
    "ghastly",
    "grotesque",
    "gruesome",
    "hard-hearted",
    "insidious",
    "insipid",
    "malicious",
    "monstrous",
    "noxious",
    "offensive",
    "oppressive",
    "pessimistic",
    "prejudice",
    "repulsive",
    "ruthless",
    "sinister",
    "vice",
    "vicious",
    "vile",
    "villainous",
    "vindictive",
]


def contar_negativas(lista_palabras):
    numero_palabras_negativas = 0
    for palabra_positiva in palabras_negativas:
        if palabra_positiva in lista_palabras:
            numero_palabras_negativas += 1

    return numero_palabras_negativas

In [156]:
reviews.apply(contar_positivas)

0       2
1       0
2       1
3       0
4       0
       ..
1795    2
1796    0
1797    1
1798    0
1799    0
Name: review, Length: 1800, dtype: int64

In [157]:
reviews.apply(contar_negativas)

0       0
1       0
2       2
3       0
4       0
       ..
1795    0
1796    0
1797    0
1798    0
1799    1
Name: review, Length: 1800, dtype: int64

In [158]:
df_reviews["Positive"]=reviews.apply(contar_positivas)
df_reviews["Negative"]=reviews.apply(contar_negativas)
df_reviews

,Unnamed: 0.1,Unnamed: 0,book_title,date,rname,rating,review,likes,stars_given,Positive,Negative
0,0,0,Dune,"Mar 22, 2011",Rajat Ubhaykar,it was amazing,"In my head, the purpose of this review is very...",1130,5.0,2,0
1,1,1,Dune,"Apr 29, 2014",Jay,did not like it,If this is the gold standard against which all...,1302,1.0,0,0
2,2,2,Dune,"Nov 20, 2008",Manny,really liked it,There's a characteristically witty essay by Bo...,1890,4.0,1,2
3,3,3,Dune,"Jun 24, 2007",John Wiswell,it was ok,No one should argue the importance Dune. It la...,1409,2.0,0,0
4,4,4,Dune,"Nov 13, 2021",Lala BooksandLala,it was amazing,just when you thought 2021 couldn't get any we...,974,5.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1795,1795,1795,Neuromancer,"Jan 23, 2013",Lit Bug,really liked it,Neuromancer is a seminal archetypal cyberpunk ...,11,4.0,2,0
1796,1796,1796,Neuromancer,"Sep 28, 2014",David Sarkies,it was ok,A journey into the heart of the machine4 Octob...,11,2.0,0,0
1797,1797,1797,Neuromancer,"Jul 07, 2014",Michael Emond,it was amazing,I decided to revisit this sci-fi classic I had...,11,5.0,1,0
1798,1798,1798,Neuromancer,"Nov 02, 2019",Oleksandr Zholud,really liked it,"This is the book that spawned the genre, cyber...",11,4.0,0,0
1799,1799,1799,Neuromancer,"Sep 13, 2016",Jonathan Pool,it was amazing,Historical & Literary contextI first read Neur...,10,5.0,0,1

5.-Implemente la funci√≥n `detectar_sentimientos` que toma como entrada una fila del dataframe y retorna el sentimiento de cada oraci√≥n. La condici√≥n que debe verificar es que:

- $positiva - negativa = 0$, entonces retorna `undefined`.
- $positiva > negativa$, entonces retorna 'positive'.
- $positiva < negativa$, entonces retorna `negative`.

Aplique la funci√≥n detectar_sentimientos sobre las filas del dataset para calcular el sentimiento de cada review. Luego, asigne la serie generada al dataframe original.

In [159]:
def detectar_sentimientos(fila):
  positiva=fila["Positive"]
  negativa=fila["Negative"]
  if positiva-negativa==0:
    return "undefined"
  elif positiva > negativa:
    return "positive"
  else:
    return "negative"

In [160]:
sentimiento=df_reviews.apply(detectar_sentimientos,axis=1)
sentimiento

0        positive
1       undefined
2        negative
3       undefined
4       undefined
          ...
1795     positive
1796    undefined
1797     positive
1798    undefined
1799     negative
Length: 1800, dtype: object

In [161]:
df_reviews["Sentimiento"]=sentimiento
df_reviews

,Unnamed: 0.1,Unnamed: 0,book_title,date,rname,rating,review,likes,stars_given,Positive,Negative,Sentimiento
0,0,0,Dune,"Mar 22, 2011",Rajat Ubhaykar,it was amazing,"In my head, the purpose of this review is very...",1130,5.0,2,0,positive
1,1,1,Dune,"Apr 29, 2014",Jay,did not like it,If this is the gold standard against which all...,1302,1.0,0,0,undefined
2,2,2,Dune,"Nov 20, 2008",Manny,really liked it,There's a characteristically witty essay by Bo...,1890,4.0,1,2,negative
3,3,3,Dune,"Jun 24, 2007",John Wiswell,it was ok,No one should argue the importance Dune. It la...,1409,2.0,0,0,undefined
4,4,4,Dune,"Nov 13, 2021",Lala BooksandLala,it was amazing,just when you thought 2021 couldn't get any we...,974,5.0,0,0,undefined
...,...,...,...,...,...,...,...,...,...,...,...,...
1795,1795,1795,Neuromancer,"Jan 23, 2013",Lit Bug,really liked it,Neuromancer is a seminal archetypal cyberpunk ...,11,4.0,2,0,positive
1796,1796,1796,Neuromancer,"Sep 28, 2014",David Sarkies,it was ok,A journey into the heart of the machine4 Octob...,11,2.0,0,0,undefined
1797,1797,1797,Neuromancer,"Jul 07, 2014",Michael Emond,it was amazing,I decided to revisit this sci-fi classic I had...,11,5.0,1,0,positive
1798,1798,1798,Neuromancer,"Nov 02, 2019",Oleksandr Zholud,really liked it,"This is the book that spawned the genre, cyber...",11,4.0,0,0,undefined
1799,1799,1799,Neuromancer,"Sep 13, 2016",Jonathan Pool,it was amazing,Historical & Literary contextI first read Neur...,10,5.0,0,1,negative

### Trabajo con Fechas

1.- Convierta la columna `date` a una serie de datetimes y luego ordenarla.

In [162]:
df_date=df_reviews["date"]
df_date

0       Mar 22, 2011
1       Apr 29, 2014
2       Nov 20, 2008
3       Jun 24, 2007
4       Nov 13, 2021
            ...
1795    Jan 23, 2013
1796    Sep 28, 2014
1797    Jul 07, 2014
1798    Nov 02, 2019
1799    Sep 13, 2016
Name: date, Length: 1800, dtype: object

In [163]:
fechas=pd.to_datetime(df_date).sort_values()
fechas

76     2006-08-29
66     2006-12-04
161    2006-12-09
1648   2006-12-29
1175   2007-03-07
          ...
663    2021-12-06
417    2021-12-17
565    2021-12-19
661    2021-12-21
510    2021-12-24
Name: date, Length: 1800, dtype: datetime64[ns]

2.-Seleccione las reviews publicadas en el a√±o 2020

In [164]:
mascara=pd.to_datetime(df_date).sort_values().dt.year ==2020
mascara

76      False
66      False
161     False
1648    False
1175    False
        ...
663     False
417     False
565     False
661     False
510     False
Name: date, Length: 1800, dtype: bool

In [165]:
df_reviews.loc[mascara]

,Unnamed: 0.1,Unnamed: 0,book_title,date,rname,rating,review,likes,stars_given,Positive,Negative,Sentimiento
16,16,16,Dune,"Jun 02, 2020",Nataliya,really liked it,"‚ÄúI have seen a friend become a worshiper, he t...",351,4.0,1,2,negative
25,25,25,Dune,"Nov 07, 2020",Lisa of Troy,it was amazing,If you are having a hard time reading Dune:htt...,237,5.0,0,0,undefined
26,26,26,Dune,"Sep 10, 2020",Jonathan O'Neill,really liked it,4 ‚≠êA word of warning as you venture out to per...,230,4.0,0,0,undefined
36,36,36,Dune,"Jun 17, 2020",Elle,NaN,Time to find out if I‚Äôm too dumb to understand...,158,NaN,0,0,undefined
48,48,48,Dune,"Nov 24, 2020",Johann (jobis89),really liked it,‚ÄúI must not fear. Fear is the mind-killer. Fea...,115,4.0,0,2,negative
...,...,...,...,...,...,...,...,...,...,...,...,...
1742,1742,1742,Neuromancer,"Nov 29, 2020",Bernardo,really liked it,Neuromancer was the book that started the cybe...,32,4.0,0,0,undefined
1743,1743,1743,Neuromancer,"Apr 25, 2020",L.S. Popovich,liked it,"There is much to enjoy about Neuromancer, and ...",33,3.0,1,0,positive
1768,1768,1768,Neuromancer,"Jun 09, 2020",Lee Klein,liked it,Wife had this in hard cover in a pile to donat...,19,3.0,0,0,undefined
1770,1770,1770,Neuromancer,"Feb 05, 2020",Blaine,it was ok,"Science fiction is one of my favorite genres, ...",17,2.0,1,0,positive
1771,1771,1771,Neuromancer,"Jan 07, 2020",Leo Robertson,it was ok,Fuckin' what??This is my first read after the ...,17,2.0,1,0,positive

3.-Obtenga la diferencia entre la fecha de publicaci√≥n de los reviews y la fecha actual. Para esto, puede ser √∫til utilizar `datetime.now()`.

In [168]:
from datetime import datetime
today=datetime.now()

In [169]:
diferencia=(today-fechas)
diferencia

76     6224 days 17:48:41.824885
66     6127 days 17:48:41.824885
161    6122 days 17:48:41.824885
1648   6102 days 17:48:41.824885
1175   6034 days 17:48:41.824885
                  ...
663     646 days 17:48:41.824885
417     635 days 17:48:41.824885
565     633 days 17:48:41.824885
661     631 days 17:48:41.824885
510     628 days 17:48:41.824885
Name: date, Length: 1800, dtype: timedelta64[ns]

4.-Utilizando la diferencia obtenida en el punto anterior, obtenga diferencia m√°xima y m√≠nima.

In [170]:
maximo=max(diferencia)
maximo

Timedelta('6224 days 17:48:41.824885')

In [171]:
minimo=min(diferencia)
minimo

Timedelta('628 days 17:48:41.824885')

5.-En base al diferencia m√°xima del punto 4, transforme este valor a solo:

- segundos.
- dias.

In [172]:
f"{maximo.days} days"

'6224 days'

In [173]:
f"{maximo.total_seconds()} seconds"

'537817721.824885 seconds'

4.-Calcule el promedio de d√≠as en que no son publicados reviews, para esto utilice solo la columna `date`.

In [174]:
fechas.value_counts()

2018-03-07    10
2013-01-08     7
2013-03-25     6
2008-11-20     6
2011-07-30     5
              ..
2014-01-24     1
2014-01-20     1
2014-01-19     1
2014-01-17     1
2021-12-24     1
Name: date, Length: 1443, dtype: int64

In [175]:
con_reviews=len(fechas.value_counts())
con_reviews

1443

In [180]:
total_days=maximo-minimo
total=total_days.days
total

5596

In [182]:
sin_reviews=total-con_reviews
sin_reviews

4153

In [184]:
promedio=sin_reviews/total
promedio

0.7421372408863474

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87110296-876e-426f-b91d-aaf681223468' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>