In [1]:
!apt install postgresql postgresql-contrib &>log
!service postgresql start
!sudo -u postgres psql -c "CREATE USER root WITH SUPERUSER"
!pip install pgspecial

 * Starting PostgreSQL 14 database server
   ...done.
CREATE ROLE
Collecting pgspecial
  Downloading pgspecial-2.1.0-py3-none-any.whl (35 kB)
Requirement already satisfied: click>=4.1 in /usr/local/lib/python3.10/dist-packages (from pgspecial) (8.1.7)
Requirement already satisfied: sqlparse>=0.1.19 in /usr/local/lib/python3.10/dist-packages (from pgspecial) (0.4.4)
Collecting psycopg>=3.0.10 (from pgspecial)
  Downloading psycopg-3.1.12-py3-none-any.whl (171 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.5/171.5 kB 7.6 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.1 in /usr/local/lib/python3.10/dist-packages (from psycopg>=3.0.10->pgspecial) (4.5.0)
Installing collected packages: psycopg, pgspecial
Successfully installed pgspecial-2.1.0 psycopg-3.1.12

In [2]:
%load_ext sql
%config SqlMagic.feedback=False
%config SqlMagic.autopandas=True
%sql postgresql+psycopg2://diplo:diplo_python@lin-29996-12677-pgsql-primary.servers.linodedb.net:5432/viajes

In [3]:
import psycopg2
import pandas as pd

In [4]:
db_dict = {
    'host': 'lin-29996-12677-pgsql-primary.servers.linodedb.net',
    'database': 'viajes',
    'user': 'diplo',
    'password': 'diplo_python',
    'port': '5432'
}
conn = psycopg2.connect(**db_dict)

In [5]:
#Exploramos la base de datos
%%sql
SELECT *
FROM transparencia
LIMIT 3;

 * postgresql+psycopg2://diplo:***@lin-29996-12677-pgsql-primary.servers.linodedb.net:5432/viajes

,anho,mes,nombres,apellidop,apellidom,estudios,fecha_inicio,fecha_fin,programa,regimen,cargo,cargo2,grado,monto
0,2015,1,Laura Del Carmen,Aballay,Garrido,SIN INFORMACIÃN,2011-09-01,2015-12-31,Programa AcadÃ©mico de Bachillerato,CONTRATA,AUXILIAR,AUXILIAR,24,667712
1,2015,1,Francisco Javier Leonel,Abalo,Cea,MAGÃSTER,2008-02-01,2015-12-31,Facultad de FilosofÃ­a y Humanidades,CONTRATA,ACADÃMICO,INSTRUCTOR,10,575249
2,2015,1,Isabel Margarita,Abarca,Baeza,MAGÃSTER,2015-01-01,2015-12-31,Instituto de NutriciÃ³n y TecnologÃ­a de los A...,CONTRATA,ACADÃMICO,PROF. ADJUNTO,9,93453

In [6]:
#P0. Escriba una consulta SQL para obtener los salarios mensuales de todos los empleados que tengan un apellido
#paterno elegido por usted, ordenados por monto.
#Elegí imprimir más datos que sólo el monto
%%sql
SELECT nombres, apellidop, apellidom, monto
FROM transparencia
WHERE apellidop LIKE '%Verdugo%'
ORDER BY monto

 * postgresql+psycopg2://diplo:***@lin-29996-12677-pgsql-primary.servers.linodedb.net:5432/viajes

               nombres apellidop apellidom    monto
0      Alejandro Isaac   Verdugo     Palma    73217
1      Alejandro Isaac   Verdugo     Palma    73217
2      Alejandro Isaac   Verdugo     Palma    73217
3      Alejandro Isaac   Verdugo     Palma    73217
4      Alejandro Isaac   Verdugo     Palma    73217
..                 ...       ...       ...      ...
522  Ricardo Alejandro   Verdugo   Salgado  3012247
523  Ricardo Alejandro   Verdugo   Salgado  3044247
524  Ricardo Alejandro   Verdugo   Salgado  3509381
525  Ricardo Alejandro   Verdugo   Salgado  3757678
526  Ricardo Alejandro   Verdugo   Salgado  3884951

[527 rows x 4 columns]

In [7]:
#Exploramos la base de datos
%%sql
SELECT *
FROM notas

 * postgresql+psycopg2://diplo:***@lin-29996-12677-pgsql-primary.servers.linodedb.net:5432/viajes

    id                                           nombre  nota
0    4  Quijada Mateluna, Francisca Victoria del Carmen   5.1
1    5             Martinez Garrido, Gabriela Alejandra   4.7
2    6                      Filippini Puttini, Giuliano   5.5
3    7                Calderon Leiva, Gonzalo Sebastian   4.9
4    8                   Valdes Rubilar, Gustavo Arturo   3.3
5    9           Villarroel Ramirez, Jenifer Del Carmen   6.2
6   10               Gascon Pérez, Militza Angela Lucia   5.3
7    2              Hermosilla Varela, Dominique Isabel   6.2
8    3                    Cotoras Straub, Dusan Alfredo   3.6
9    1              Mancilla Almonacid, Daniela Francis   4.0
10  11                  Vucina Martinez, Miroslav Mario   7.0

In [8]:
#P0. Escriba una consulta SQL que obtenga su nota final del ramo.
%%sql
SELECT nota
FROM notas
WHERE nombre LIKE '%Mancilla%'

 * postgresql+psycopg2://diplo:***@lin-29996-12677-pgsql-primary.servers.linodedb.net:5432/viajes

   nota
0   4.0

In [9]:
#P1. Escriba un código que pida un apellido usando input().
#Genere una query que entregue los diez sueldos más altos de empleados con ese apellido.
#Escogí Leon
apellido=input()
query= "SELECT nombres, apellidop, apellidom, monto FROM transparencia WHERE apellidop = '"+apellido+"' ORDER BY monto DESC LIMIT 10"
pd.read_sql_query(query,conn)

Leon

<ipython-input-9-e459ad2cfc54>:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(query,conn)

            nombres apellidop apellidom    monto
0  Patricio Rodrigo      Leon      Diaz  5693828
1         Alejandro      Leon   Stewart  5115987
2     Boris Marcial      Leon     Rocha  4990419
3         Alejandro      Leon   Stewart  4735402
4         Alejandro      Leon   Stewart  4687602
5         Alejandro      Leon   Stewart  4671287
6         Alejandro      Leon   Stewart  4610602
7         Alejandro      Leon   Stewart  4455259
8         Alejandro      Leon   Stewart  4348603
9         Alejandro      Leon   Stewart  4044489

In [ ]:
#P2. Usted debe ejecutar la celda e ingresar un ataque de SQL injection para subir su nota registrada en notas.

In [10]:
#SIN ATAQUE ingresar Mancilla
apellido=input()
query= "SELECT nota FROM notas WHERE nombre LIKE '%"+apellido+"%'"
pd.read_sql_query(query,conn)

Mancilla

<ipython-input-10-6b334e521346>:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(query,conn)

   nota
0   4.0

In [11]:
conn.commit()

In [12]:
#Verificamos que no cambió
%%sql
SELECT nota
FROM notas
WHERE nombre LIKE '%Mancilla%'

 * postgresql+psycopg2://diplo:***@lin-29996-12677-pgsql-primary.servers.linodedb.net:5432/viajes

   nota
0   4.0

In [13]:
#CON ATAQUE ingresar Mancilla%'; UPDATE notas SET nota = '7.0' WHERE nombre LIKE '%Mancilla%' --
apellido=input()
query= "SELECT nota FROM notas WHERE nombre LIKE '%"+apellido+"%'"
pd.read_sql_query(query,conn)

Mancilla%'; UPDATE notas SET nota = '7.0' WHERE nombre LIKE '%Mancilla%' --

<ipython-input-13-2ae52718b39a>:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(query,conn)

TypeError: ignored

In [14]:
conn.commit()

In [15]:
#Verifiquemos que cambió
%%sql
SELECT nota
FROM notas
WHERE nombre LIKE '%Mancilla%'

 * postgresql+psycopg2://diplo:***@lin-29996-12677-pgsql-primary.servers.linodedb.net:5432/viajes

   nota
0   7.0

In [ ]:
#P3. En otra celda, escriba la misma funcionalidad, pero esta vez, de forma segura ante SQL
#injections. Pruebe que al re-ingresar la inyección del problema anterior, esta vez su nota no cambia.

In [16]:
#SIN ATAQUE ingresar Mancilla
apellido=input()
query= "SELECT nota FROM notas WHERE nombre LIKE %s"
pd.read_sql_query(query,conn,params=['%'+apellido+'%'])

Mancilla

<ipython-input-16-914acd35ec3f>:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(query,conn,params=['%'+apellido+'%'])

   nota
0   7.0

In [17]:
conn.commit()

In [20]:
#CON ATAQUE ingresar Mancilla%'; UPDATE notas SET nota = '1.0' WHERE nombre LIKE '%Mancilla%' --
apellido=input()
query= "SELECT nota FROM notas WHERE nombre LIKE %s"
pd.read_sql_query(query,conn,params=['%'+apellido+'%'])

Mancilla%'; UPDATE notas SET nota = '1.0' WHERE nombre LIKE '%Mancilla%' --

<ipython-input-20-981e2f43891a>:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(query,conn,params=['%'+apellido+'%'])

Empty DataFrame
Columns: [nota]
Index: []

In [21]:
conn.commit()

In [22]:
#Verificamos que no cambió
%%sql
SELECT nota
FROM notas
WHERE nombre LIKE '%Mancilla%'

 * postgresql+psycopg2://diplo:***@lin-29996-12677-pgsql-primary.servers.linodedb.net:5432/viajes

   nota
0   7.0